
name: Deploy to GitHub Pages

on:
  # mainブランチにプッシュされた時に実行
  push:
    branches: [ main ]
  # GitHubの画面から手動でも実行できるようにする
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # pnpmを使っていることを明示する（超重要！）
        with:
          package-manager: pnpm@10
          node-version: 22
        env:
          PNPM_ONLY_BUILT_DEPENDENCIES: esbuild,sharp


  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
